name: gdal_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7  
  - gdal
  - pip
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - fiona
  - shapely
  - opencv=4.5.5
  - pyshp
  - scikit-image
  - pyproj
  - pip:
    - tensorflow
    - keras