name: geo_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - h5py
  - gdal
  - fiona
  - shapely
  - pyproj
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - opencv
  - pyshp
  - scikit-image
  - pip